/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.dsl.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

import br.ufes.inf.nemo.ontouml.dsl.xtext.CustomValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OntoDSLRuntimeModule extends br.ufes.inf.nemo.ontouml.dsl.xtext.AbstractOntoDSLRuntimeModule {
	//Registra o meu ValueConverter
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return CustomValueConverter.class;
    }
}
