/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DslOntoUMLUiModule extends br.ufes.inf.nemo.ontouml.dsl.ui.AbstractDslOntoUMLUiModule {
	public DslOntoUMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
