/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.dsl.xtext.ui.contentassist;

import br.ufes.inf.nemo.ontouml.dsl.xtext.ui.contentassist.AbstractOntoDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OntoDSLProposalProvider extends AbstractOntoDSLProposalProvider {

}
