/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslOntoUMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.ufes.inf.nemo.ontouml.dsl.ui.internal.DslOntoUMLActivator.getInstance().getInjector("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML");
	}
	
}
