/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.dsl;

import br.ufes.inf.nemo.ontouml.dsl.CustomValueConverter;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslOntoUMLRuntimeModule extends br.ufes.inf.nemo.ontouml.dsl.AbstractDslOntoUMLRuntimeModule {

	//Registra o meu ValueConverter
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return CustomValueConverter.class;
    }
	
}
