
/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.dsl.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class DslOntoUMLActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static DslOntoUMLActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML")).with(getUiModule("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static DslOntoUMLActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML".equals(grammar)) {
		  return new br.ufes.inf.nemo.ontouml.dsl.DslOntoUMLRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("br.ufes.inf.nemo.ontouml.dsl.DslOntoUML".equals(grammar)) {
		  return new br.ufes.inf.nemo.ontouml.dsl.ui.DslOntoUMLUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
