/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.dsl.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class OntoDSLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
