/*
 * generated by Xtext
 */
package br.ufes.inf.nemo.ontouml.dsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OntoDSLUiModule extends br.ufes.inf.nemo.ontouml.dsl.xtext.ui.AbstractOntoDSLUiModule {
	public OntoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
