/*
* generated by Xtext
*/
package br.ufes.inf.nemo.ontouml.dsl.ui.contentassist;

import br.ufes.inf.nemo.ontouml.dsl.ui.contentassist.AbstractDslOntoUMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DslOntoUMLProposalProvider extends AbstractDslOntoUMLProposalProvider {

}
